apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: travel-api
  name: travel-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: travel-api
  replicas: 1
  template:
    metadata:
      labels:
        app: travel-api
    spec:
      containers:
      - image: lucasbarross/travel-api:latest
        name: travel-api
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: travel-api
  namespace: default
  labels:
    service: travel-api
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: travel-api
